project:
  type: website
  output-dir: docs
website:
  title: "Hello"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Skills.qmd
      - Projects.qmd
      - midproject.qmd
      - code.qmd
      - finalproj.qmd
      - final project code.qmd

format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual 

